@startuml refresh-access-token

skinparam monochrome true
skinparam shadowing false
skinparam ParticipantPadding 30


title Get new access token

participant Partner
participant Swedbank

autonumber 1
Partner->Swedbank: Make any request

Swedbank-->Partner: Response
opt TOKEN_INVALID error received?
Partner->Swedbank: POST/token with grant-type=refresh_token (check Swagger)
Swedbank-->Partner: New access token
Partner->Swedbank: Repeat request with new access token
Swedbank-->Partner: Response
end
Partner->Partner: Handle response

@enduml
